### ISSUE TITLE
Box shortcode title on new line and margin too large?

### ISSUE THREAD

**Issue by alexisdrakopoulos** [RoneoOrg/hugo-shortcode-roneo-collection#1]
<img width="848" alt="Screenshot 2023-02-18 at 15 11 35" src="https://user-images.githubusercontent.com/33128441/219873374-7659c8ee-10c1-4cf4-8a3c-3dc5f1f9bdb3.png">

I couldn't see whether my personal CSS is somehow messing with it, but I'm a newbie when it comes to anything frontend.

Code:
```
{{< box info >}}
Test

test
{{< /box >}}

{{< box warning >}}
hello

testing
{{< /box >}}
```

**Comment by RoneoOrg** [comment]
Please try

```
{{< box info >}} Test

test
{{< /box >}}
```

and

```
{{< box info >}} ## Test

test
{{< /box >}}
```

to get a title on the first line
