### ISSUE TITLE
Icons in front matter

### ISSUE THREAD

**Issue by mattomis** [RoneoOrg/hugo-shortcode-roneo-collection#2]
What is the requirement for using icons in front matter?
It seems like the requirement is having at least two files to create a partials template in /layouts/partials that defines what icons will be references in the front matter and for which keys. Those files are _ico.html and ico.html. 
In my case I created a folder in my project called partials in layouts, and then created a file called ico.html but I have no idea what is supposed to go in that file or in _ico.html other than MAYBE exactly whatever is in those files in this github project. I mean I have found [something here](https://phoni.es/dev/ico/) that says you need to have some text along the lines of:
`{{ .Params.icon | markdownify }}` but I have no idea how to use that information in creating the template(s).

If you want to have front matter like this:

```
---
title: "This is a title preceded by an icon in the sidebar"
icon: {{< ico inbox-full>}}
---
```
But I do not see how these things work together to produce the desired effect.

**Comment by RoneoOrg** [comment]
This is discussed on [discourse.gohugo.io](https://discourse.gohugo.io/t/using-icons-in-front-matter-via-icon-mdi-inbox-full-does-not-work-as-expected/45442)
