### ISSUE TITLE
Warning: Too many open files / "Hugo Server" command

### ISSUE THREAD

**Issue by Bas-Man** [RoneoOrg/hugo-shortcode-roneo-collection#3]
Hi.
I am just taking a look at this. Unfortunately when I run `hugo server` I get the following error.

```sh
Built in 3 ms
Error: error building site: failed to acquire a build lock: open /Users/aspann/Documents/Development/hugo/bas-man.dev/.hugo_build.lock: too many open files
```

No error when I run `hugo`

is there a fix for this.

My config has the following

```toml
theme = [ "hugo-shortcode-roneo-collection", "hugo-notice", "beautifulhugo" ]
```

I hope to remove the `hugo-notice` if this looks good.

Thanks

**Comment by RoneoOrg** [comment]
Could you please try to:

- delete `/Users/aspann/Documents/Development/hugo/bas-man.dev/.hugo_build.lock` and run again
- check the following pages:
- https://github.com/gohugoio/hugo/issues/6109
- https://discourse.gohugo.io/t/what-is-the-hugo-build-lock-file/35417
- https://discourse.gohugo.io/t/error-hugo-0-52-too-many-open-files/17653/17
- https://github.com/gohugoio/hugo/issues/8166

It seems to be sometime related to the OS you're using, please complete your report if the previous pages didn't allow to fix this issue

**Comment by Bas-Man** [comment]
Thanks. I tried the first option earlier. With no luck. I will look at your suggestions. I also agree it's OS Specific. MacOS.

**Comment by Bas-Man** [comment]
The links you provided solved the general issue.
