### ISSUE TITLE
Whitespace on default icons in theme/layouts files

### ISSUE THREAD

**Issue by thehoegh** [RoneoOrg/hugo-shortcode-roneo-collection#5]
I'm trying to include an icon in a template file
```
<div class="book-brand">
  <h3>
    {{ partial "ico" "star" }}
    <span>{{ .Site.Title }}</span>
  </h3>
</div>
```

This works, but the icon included has a couple of pixels with whitespace, resulting in a somewhat off-base visual of the result:
![image](https://github.com/RoneoOrg/hugo-shortcode-roneo-collection/assets/4199918/30b5b4fe-af16-46c9-b223-cf762258ed30)

How can I get the proper alignment?

**Comment by c2tz** [comment]
You should make a modification in your CSS, add `vertical-align` baseline or middle property : [https://developer.mozilla.org/en-US/docs/Web/CSS/vertical-align](https://developer.mozilla.org/en-US/docs/Web/CSS/vertical-align)

**Comment by RoneoOrg** [comment]
Thanks @c2tz! 
@holene Does it fix you issue?
Let me know if I should add some lines of CSS to the default source code.

**Comment by thehoegh** [comment]
@c2tz @RoneoOrg I'm *so* sorry for not replying sooner – I quickly mitigated the entire situation by removing the problem, thus forgetting about it 😅  I hope my input was of some value for you, if not, I apologize for wasting your time 🙃

**Comment by RoneoOrg** [comment]
Thanks for the update, I consider this issue as resolved then closing
Cheers
